default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  REGISTRY: registry.kube-system.svc.cluster.local:5000
# before_script:
  # - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

stages:
  - build
  - deploy

build-docker:
  stage: build
  # image: gitlab/dind
  tags:
    - contabo
  script:
    - docker build -t $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH .
    - docker push $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH

apply-kubectl:
  stage: deploy
  tags:
    - contabo
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  dependencies:
    - build-docker
  script:
    - kubectl apply -f kubernetes/
  environment: production