variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ''

stages:
  - build
  - deploy

build-job:
  stage: build
  image: gitlab/dind
  tags:
    - contabo
  services:
    - docker:dind
  script:
    - docker build -t registry.kube-system.svc.cluster.local/tradingbot22-tradingbots-prefect:latest .

build-push:
  stage: build
  image: gitlab/dind
  tags:
    - contabo
  dependencies:
    - build-job
  services:
    - docker:dind
  script:
    - docker push registry.kube-system.svc.cluster.local/tradingbot22-tradingbots-prefect:latest

apply-kubectl:
  stage: deploy
  tags:
    - contabo
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  dependencies:
    - build-push
  script:
    - kubectl apply -f kubernetes/
  environment: production