build-job:
  stage: build
  image: gitlab/dind
  services:
    - docker:dind
  script:
    - docker build -t registry.kube-system.svc.cluster.local/tradingbot22-tradingbots-prefect:latest .

build-push:
  stage: build
  image: gitlab/dind
  dependencies:
    - build-job
  services:
    - docker:dind
  script:
    - docker push registry.kube-system.svc.cluster.local/tradingbot22-tradingbots-prefect:latest

apply-kubectl:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  dependencies:
    - build-push
  script:
    - kubectl apply -f kubernetes/
  environment: production