################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
# copyright
copyright = "Copyright by DataFortress.cloud UG"

# <a target="_blank" rel="noopener noreferrer" href="">

################################### French language #####################################
[de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 2

[de.params]
# copyright
home = "Home"
copyright = "Copyright by DataFortress.cloud UG"