############# English navigation ##############

# main menu
[[main]]
weight = 1
name = "Home"

[[main]]
name = "Top 10"
url = "top/"
weight = 2

[[main]]
name = "How It Works"
url = "how-it-works/"
weight = 4

[[main]]
name = "Strategies"
url = "blog/"
weight = 5

[[main]]
name = "Pricing"
url = "pricing/"
weight = 6

[[main]]
weight = 7
name = "Legal"
hasChildren = true

  [[main]]
  parent = "Legal"
  name = "Terms & Conditions"
  url = "terms-and-conditions/"
  weight = 7

  [[main]]
  parent = "Legal"
  name = "Privacy Policy"
  url = "privacy-policy/"
  weight = 11

  [[main]]
  parent = "Legal"
  name = "Imprint"
  url = "imprint/"
  weight = 13

  
[[main]]
name = "Contact"
url = "contact/"
weight = 8



### footer menus
# footer_menu_1



# footer_menu_2
[[footer_menu_2]]
name = "Prices"
url = "pricing/"
weight = 1

[[footer_menu_2]]
name = "Strategies"
url = "strategies/"
weight = 2

[[footer_menu_2]]
name = "Contact"
url = "contact/"
weight = 3


# footer_menu_3
[[footer_menu_3]]
name = "Contact"
url = "contact/"
weight = 1

[[footer_menu_3]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2

[[footer_menu_3]]
name = "Terms & Conditions"
url = "privacy-policy/"
weight = 3

[[footer_menu_3]]
name = "Imprint"
url = "imprint/"
weight = 4
