apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefectagent-deployment
  namespace: tradingbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradingbot
  template:
    metadata:
      labels:
        app: tradingbot
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: tradingbot-prefect
          image: registry.k8s.datafortress.cloud/tradingbot22-tradingbots-prefect:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "5Mi"
              cpu: "5m"
          env:
            - name: PREFECT_API_URL
              valueFrom:
                secretKeyRef:
                  name: prefectagent
                  key: PREFECT_API_URL
            - name: PREFECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prefectagent
                  key: PREFECT_API_KEY
            - name: FINNHUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prefectagent
                  key: FINNHUB_API_KEY
            - name: PSQL_URL
              valueFrom:
                secretKeyRef:
                  name: prefectagent
                  key: PSQL_URL
