name: Deploy a Prefect flow
on:
  push:
    branches:
      - main
jobs:
  deploy_flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      
      - name: Install prefect pip package
        run: pip install prefect

      - name: install every other unused dependency due to bad coding of prefect
        # apparently to just deploy a flow, you need to install every dependency -> again the superb efficient egineering of prefect in action
        run: pip install -r requirements.txt

      - name: Prefect Auth Login
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: justin-df/default

      - name: Prefect Deploy Script
        run: ./prefectAddDeployment.sh
